server:
  port: 8901

spring:
  application:
    name: blog-center
  cloud:
    consul:
      port: 8500 # consul代理端口
      host: 39.98.80.78 # consul代理ip
      enabled: true #启用 spring cloud consul
      discovery:
        # 配置服务注册到Consul上
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 配置注册到consul 服务的id
        register: true # 是否开启在 consul 中注册服务
        health-check-path: /actuator/health   #定义 consul 健康检查路径
        health-check-interval: 10s # consul 健康检查频率
        enabled: true #启用 consul 服务发现
        service-name: ${spring.application.name} #设置 注册到 consul 的服务名称
        ip-address: ${spring.cloud.client.ip-address} # 访问服务时使用的 ip地址 （还必须设置preferIpAddress才能使用）
        prefer-ip-address: true
#  datasource:
#    username: root
#    password: NeuMobile123$
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    mapUnderscoreToCamelCase: true
#  type-aliases-package: com.James.blog.pojo
#  mapper-location: classpath:com/James/blog/mapper/*.xml



